name: flutter_taller1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  http: ^0.13.6
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.1
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true